name: AsyncAPI documents processing

on:
  push:
    tags:
      - v1.**

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generating HTML from my AsyncAPI document
        uses: docker://asyncapi/github-action-for-generator:2.0.3
        with:
          template: '@asyncapi/html-template@0.24.9'
          filepath: asyncapi.yml
          output: docs

      - name: Modify path to js and css files
        run: |
          sudo sed -i 's#css/global.min.css#global.min.css#g' docs/index.html
          sudo sed -i 's#css/asyncapi.min.css#asyncapi.min.css#g' docs/index.html
          sudo sed -i 's#js/asyncapi-ui.min.js#asyncapi-ui.min.js#g' docs/index.html
        shell: bash

      - name: Commit files to auto_generated_doc branch
        uses: GuillaumeFalourd/copy-push-files@v1
        with:
          target_branch: auto_generated_doc
          target_dir: docs/${{github.ref_name}}
          commit_message: 'Auto-commit from Github Action'
          source_files: docs/index.html docs/js/asyncapi-ui.min.js docs/css/asyncapi.min.css docs/css/global.min.css
          remote_repository: https://github.com/RuterNo/adt-doc
          access_token: ${{ secrets.GITHUB_TOKEN }}

