name: CI workflow

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  RELEASE_NAME: 2.x

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generating HTML from my AsyncAPI document
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install -g @asyncapi/generator@1.9.18
      - run: ag asyncapi/asyncapi.yml @asyncapi/html-template@0.28.4 -o docs/asyncapi --force-write

      - name: Modify HTML output from generator
        run: |
          sudo sed -i 's/version\.from\.tag/'"$RELEASE_NAME"'/g' docs/asyncapi/index.html
          sudo cp asyncapi/stylesheets/doc.css docs/asyncapi/css/
          sudo sed -i -e '\@</head>@i\<link href="css/doc.css" rel="stylesheet">' docs/asyncapi/index.html
        shell: bash

      - name: Make Json Schemas available
        run: |
          sudo cp -r asyncapi/json-schemas docs/asyncapi/json-schemas
          sudo find docs/asyncapi/json-schemas/ -name "*example.json" -type f -delete
          sudo find docs/asyncapi/json-schemas/ -name "*.meta.json" -type f -delete
          sudo find docs/asyncapi/json-schemas/ -name "*.md" -type f -delete
        shell: bash

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mike
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin gh-pages --depth=1
      - run: mike deploy --push $RELEASE_NAME
